version: '3.8'
services:
  app:
    image: address-suggestion-proxy:local
    restart: unless-stopped
    ports:
      - '8080:8080'
    command:
      - /app/address-suggestion-proxy
    volumes:
      - ./config.toml:/app/config.toml:ro
    networks:
      backend:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      backend:
volumes:
  cache:
    driver: local
networks:
  backend: