version: '3.8'
services:
  app:
    image: address-suggestion-proxy:local
    restart: unless-stopped
    ports:
      - '8080:8080'
    working_dir: /app
    entrypoint: ["go", "run", "."]
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - backend
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=password
    ports:
      - '6379:6379'
    volumes:
      - suggestion-redis:/bitnami/redis/data
    networks:
      - backend
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=password
    ports:
      - '26379:26379'
    depends_on:
      - redis
    networks:
      - backend
volumes:
  suggestion-redis:
    driver: local
networks:
  backend:
    driver: bridge